/**
 * ClickUp user id to display metadata.
 *
 * GENERATED by scripts/generate-roster.js from ClickUp workspace 9011561475,
 * then hand-edited for titles and committed. Do not hand-enter user ids.
 *
 * This file is the only source of names, titles and images that reach the
 * client. ClickUp is authoritative for exactly one thing: which user ids logged
 * matched time. A teammate can rename their ClickUp account or change their
 * avatar at any time, so nothing ClickUp-sourced is ever rendered.
 *
 * The roster is agency-wide, not per-client: the report already filters to
 * users who logged time against the configured folders, so one roster serves
 * every client this app is pointed at.
 */
export const ROSTER = {
  '81552507': {
    name:   "Jamie Lukey",
    title:  '',
    roster: '/team/roster/jamie.webp',
    stack:  '/team/stack/jamie.webp',
    active: true
  },
  '81327662': {
    name:   "Josh Titus",
    title:  '',
    roster: '/team/roster/titus.webp',
    stack:  '/team/stack/titus.webp',
    active: true
  },
  '81549208': {
    name:   "Sasha Beck",
    title:  '',
    roster: '/team/roster/sasha.webp',
    stack:  '/team/stack/sasha.webp',
    active: true
  },
  '114140375': {
    name:   "Tyler Lukey",
    title:  '',
    roster: '/team/roster/tyler.webp',
    stack:  '/team/stack/tyler.webp',
    active: true
  },
};

/**
 * Anyone contributing without a roster entry collapses into the studio mark.
 * Their real id is never rendered.
 */
export const STUDIO_FALLBACK = {
  name:   'Founding Creative',
  title:  'Studio team',
  roster: '/team/roster/fc-mark.svg',
  stack:  '/team/stack/fc-mark.svg',
  isStudio: true,
  unrostered: true
};

/**
 * A misnamed or missing file should fail loudly at module load, not render as a
 * broken image on a live client report.
 */
for (const [id, person] of Object.entries(ROSTER)) {
  for (const field of ['roster', 'stack']) {
    const value = person[field];
    if (typeof value !== 'string' || !value.trim() || !/\.(webp|svg)$/.test(value)) {
      throw new Error(
        `roster.js: ${id} (${person.name}) has an invalid "${field}" path: ${JSON.stringify(value)}`
      );
    }
  }
}
for (const field of ['roster', 'stack']) {
  const value = STUDIO_FALLBACK[field];
  if (typeof value !== 'string' || !value.trim() || !/\.(webp|svg)$/.test(value)) {
    throw new Error(`roster.js: STUDIO_FALLBACK has an invalid "${field}" path`);
  }
}
